name: RSS Runner

run-name: 'Runner #${{ github.run_number }} ${{ inputs.suffix }}'

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Input suffix'
        required: false
        type: string

  schedule:
    - cron: '0 */2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: false
        
    - name: Use node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: pnpm
        cache-dependency-path: server/pnpm-lock.yaml
    
    - name: Get pnpm cache directory
      id: pnpm-store-path
      shell: bash
      run: echo "dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

    - name: Cache modules
      id: pnpm-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.pnpm-store-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-202412-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-202412-

    - name: Install and run crawler
      working-directory: ./server
      env:
        WORKFLOW: true
        RSS_CONFIG: ${{ secrets.RSS_CONFIG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pnpm install
        pnpm run once

    - name: Build Frontend
      working-directory: ./site
      run: |
        pnpm install
        pnpm run build

    - name: Prepare Deployment Folder
      run: |
        mkdir deploy
        cp -r site/dist/* deploy/
        cp -r data deploy/
        cp -r details deploy/
        cp README.md deploy/
        cp TAGS.md deploy/

    - name: Deploy to Data Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: deploy
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "data: alchemy refinement update"
